name: Test

on:
  workflow_dispatch:


jobs:
  Check-Language-Build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.language-build-check.outputs.result }}
    steps:
    - run: |
        mkdir test
      working-directory: ${{ github.workspace }}
      
    - name: Check if language build folder exists
      shell: bash
      id: language-build-check
      run: |
        if [ ! -d "${{ github.workspace }}/test" ]
        then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi
        
  Build-Language:
    needs: Check-Language-Build
    if: needs.Check-Language-Build.outputs.result == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Build Language
      shell: cmd
      run: |
        ls
