name: Test

on:
  workflow_dispatch:


jobs:
  Check-Language-Build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.language-build-check.outputs.result }}
    steps:
    - run: |
        mkdir test
      working-directory: ${{ github.workspace }}
      
    - name: Check if language build folder exists
      id: language-build-check
      run: |
        if [ ! -d "${{ github.workspace }}/test" ]
        then
          echo "result=true" 
        else
          echo "result=false"
        fi
        
#   Build-Language:
#     needs: Check-Language-Build
#     if: needs.Check-Language-Build.outputs.result == false
#     runs-on: ubuntu-latest
#     steps:
#     - name: Build Language

#       run: |
#         ls
